# Regenerates the whole voice-over of "Blázen z Londýna: Tajná Akce" with natural-sounding neural voices
# (Microsoft Edge "Neural" voices through the free edge-tts library) instead of the robotic offline Piper voices.
#
# Setup (once):   pip install edge-tts
#                 ffmpeg must be on PATH (Windows: winget install ffmpeg)
# Run:            python tools/make_voices_neural.py            (needs internet; takes a few minutes)
#                 python tools/make_voices_neural.py --dry      (only lists what would be generated)
#                 python tools/make_voices_neural.py --only bj_01,bark_alert_A0   (just some clips)
# Writes assets/voices/*.mp3 and assets/voices.js (the clips, base64) – the game picks them up on reload.
import os, sys, json, base64, asyncio, subprocess, tempfile

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
sys.path.insert(0, HERE)
from voice_lines import LINES, BARKS

OUT = os.path.join(ROOT, 'assets', 'voices')
FF = 'ffmpeg'

# speaker -> (voice, rate, pitch, volume, extra ffmpeg filter). Czech for B. J. and London, German for the enemy.
RADIO = 'highpass=f=330,lowpass=f=3200,acompressor=threshold=-22dB:ratio=6:attack=5:release=80,volume=1.6'
ROOM = 'aecho=0.8:0.6:35:0.18'
SPK = {
    'bj':   ('cs-CZ-AntoninNeural', '-6%', '-3Hz', '+0%', 'bass=g=2'),        # the Eagle: calm, low, a little dry
    'lon':  ('cs-CZ-AntoninNeural', '-2%', '-14Hz', '+0%', RADIO),            # the colonel in London, over the radio
    'off':  ('de-DE-ConradNeural', '-4%', '-4Hz', '+0%', ''),                 # SS officer
    'offA': ('de-DE-ConradNeural', '+10%', '+2Hz', '+15%', 'acompressor=threshold=-18dB:ratio=4,volume=1.3'),
    'offM': ('de-DE-ConradNeural', '-8%', '-2Hz', '+0%', ''),
    'grd':  ('de-DE-KillianNeural', '+4%', '+0Hz', '+5%', ''),
    'zem':  ('de-AT-JonasNeural', '-10%', '-6Hz', '+0%', ROOM),               # Dr. Zeman: Viennese, slow, in his vault
    # three guard voices for the barks
    'A': ('de-DE-ConradNeural', '+0%', '+3Hz', '+0%', ''),
    'B': ('de-DE-KillianNeural', '+0%', '-4Hz', '+0%', ''),
    'C': ('de-CH-JanNeural', '+6%', '+0Hz', '+0%', ''),
}
# barks are short shouts: louder and faster when alarmed
BARK_MOOD = {'surprised': ('+6%', '+6Hz', '+5%'), 'angry': ('+14%', '+4Hz', '+25%'), 'neutral': ('+0%', '+0Hz', '+0%')}


def ff(src, dst, flt):
    af = 'silenceremove=start_periods=1:start_threshold=-45dB,areverse,silenceremove=start_periods=1:start_threshold=-45dB,areverse,apad=pad_dur=0.15'
    af += (',' + flt if flt else '') + ',loudnorm=I=-17:TP=-2'
    subprocess.run([FF, '-y', '-loglevel', 'error', '-i', src, '-af', af, '-ac', '1', '-ar', '22050', '-b:a', '48k', dst], check=True)


async def synth(lid, spk, text, mood=None):
    import edge_tts
    voice, rate, pitch, vol, flt = SPK[spk]
    if mood:
        r, p, v = BARK_MOOD.get(mood, BARK_MOOD['neutral'])
        add = lambda a, b, u: f"{int(a.rstrip(u)) + int(b.rstrip(u)):+d}{u}"
        rate, pitch, vol = add(rate, r, '%'), add(pitch, p, 'Hz'), add(vol, v, '%')
    tmp = os.path.join(tempfile.gettempdir(), f'vox_{lid}.mp3')
    for attempt in range(4):
        try:
            await edge_tts.Communicate(text, voice, rate=rate, pitch=pitch, volume=vol).save(tmp)
            break
        except Exception as e:  # the service throttles now and then
            if attempt == 3: raise
            print('  retry', lid, e); await asyncio.sleep(2 ** attempt)
    dst = os.path.join(OUT, lid + '.mp3'); ff(tmp, dst, flt); os.remove(tmp)
    return dst


def jobs():
    for L in LINES:
        yield L[0], L[1], L[2], None, (L[1], L[3] if len(L) > 3 else L[2])
    for kind, lst in BARKS.items():
        for v in 'ABC':
            for i, (text, mood) in enumerate(lst):
                yield f'bark_{kind}_{v}{i}', v, text, mood, None


async def main():
    dry = '--dry' in sys.argv
    only = None
    if '--only' in sys.argv: only = set(sys.argv[sys.argv.index('--only') + 1].split(','))
    todo = [j for j in jobs() if not only or j[0] in only]
    if dry:
        for lid, spk, text, mood, _ in todo: print(f'{lid:16s} {SPK[spk][0]:22s} {mood or "":10s} {text}')
        print(len(todo), 'clips'); return
    os.makedirs(OUT, exist_ok=True)
    for n, (lid, spk, text, mood, _) in enumerate(todo, 1):
        print(f'[{n}/{len(todo)}] {lid}: {text}'); await synth(lid, spk, text, mood)
    # rebuild assets/voices.js from every clip on disk (keeps clips not regenerated with --only)
    subs = {L[0]: [L[1], L[3] if len(L) > 3 else L[2]] for L in LINES}
    ids = [j[0] for j in jobs()]
    js = ['/* Blázen z Londýna: Tajná Akce – voice-over (Microsoft neural voices via edge-tts). Generated by tools/make_voices_neural.py */', 'window.CASTLE_VOX = {']
    for lid in ids:
        f = os.path.join(OUT, lid + '.mp3')
        if os.path.exists(f): js.append(f' "{lid}": "{base64.b64encode(open(f, "rb").read()).decode()}",')
    js[-1] = js[-1].rstrip(','); js.append('};')
    js.append('window.CASTLE_VOX_SUB = ' + json.dumps(subs, ensure_ascii=False) + ';')
    open(os.path.join(ROOT, 'assets', 'voices.js'), 'w', encoding='utf-8').write('\n'.join(js) + '\n')
    json.dump(subs, open(os.path.join(HERE, 'subs.json'), 'w', encoding='utf-8'), ensure_ascii=False, indent=1)
    print('done –', len(todo), 'clips generated, assets/voices.js rebuilt')


if __name__ == '__main__':
    asyncio.run(main())
